Add trivy result as pr comment (#32)
* Added trivy parser script, to extract the results and added to the PR comment

* fix gh action use and run mutual exclusion

* moved parser script from root

* Refactor script location, and run shell script step

* adding argument for parser

* removed unecessary files

* removed unecessary files

* debuging script not found

* removed extra checkout

* added checkout step before parser

* Missing branch ref

* modified shell script to consider null args, added debug step to check path

* print result on script

* Fail on exit 1 experiemnt

* Step to fail when critical exist - test

* Step to fail when critical exist - negative test

* Experiement with adding PR Comment

* Revert experiment, improve namings

* Fix Checkout step

* Added Trivy Scanning steps to the Python build

* removed specific branch ref in workflow checkout

* temporarly disable pipeline fail

* disabled fail on critical cve also for python

diff --git a/.github/workflows/image-python.yml b/.github/workflows/image-python.yml
--- a/.github/workflows/image-python.yml
+++ b/.github/workflows/image-python.yml
@@ -110,7 +110,45 @@ jobs:
 
     - name: Image digest
       run: echo "::notice ::Image digest ${{ steps.docker_build.outputs.digest }}"
+      
+    - name: Run Trivy vulnerability scanner
+      if: inputs.push-image
+      uses: aquasecurity/trivy-action@master
+      with:
+        image-ref: ${{github.repository}}${{env.REPOSITORY_SUFFIX}}:${{env.SHORT_SHA}}
+        format: 'json'
+        output: 'trivy-results.json'
+        ignore-unfixed: true
+      env:
+        TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+        TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
 
+    - name: Upload Trivy Reports
+      uses: actions/upload-artifact@v3
+      if: inputs.push-image
+      with:
+        name: Security Report
+        path: trivy-results.json
+        retention-days: 5
+
+    - name: Checkout Workflows Repo
+      if: inputs.push-image
+      uses: actions/checkout@v3
+      with:
+        repository: "toggleglobal/workflows"
+        token: ${{ secrets.DEPLOYER_GITHUB_TOKEN }}
+        path: workflows
+        ref: 'add-trivy-result-as-pr-comment'
+
+    - name: Run Trivy Parser
+      id: trivy-parser
+      if: inputs.push-image
+      run: ./workflows/.github/workflows/scripts/trivyresult_parser.sh trivy-results.json
+      shell: bash
+
+    # - name: Fail with Critical
+    #   if: inputs.push-image && steps.trivy-parser.outputs.stdout == 1
+    #   run: exit 1
     - name: Checkout Chart
       if: inputs.push-image
       uses: actions/checkout@v3
