disabled fail on critical cve also for python

diff --git a/.github/workflows/image-python.yml b/.github/workflows/image-python.yml
--- a/.github/workflows/image-python.yml
+++ b/.github/workflows/image-python.yml
@@ -141,9 +141,9 @@ jobs:
       run: ./workflows/.github/workflows/scripts/trivyresult_parser.sh trivy-results.json
       shell: bash
 
-    - name: Fail with Critical
-      if: inputs.push-image && steps.trivy-parser.outputs.stdout == 1
-      run: exit 1
+    # - name: Fail with Critical
+    #   if: inputs.push-image && steps.trivy-parser.outputs.stdout == 1
+    #   run: exit 1
     - name: Checkout Chart
       if: inputs.push-image
       uses: actions/checkout@v3
